# -*- coding: utf-8 -*-
"""
2026年度 第1回（土曜準会場）英検5級 data.json
大問1（vocabulary型）Q1〜15 — 解説・和訳付き
"""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

DATA_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "data", "grade5", "2026-1-sat", "data.json",
)

section1 = {
    "name": "大問1",
    "nameEn": "Part 1",
    "type": "vocabulary",
    "instruction": "次の(1)から(15)までの( )に入れるのに最も適切なものを1, 2, 3, 4の中から一つ選び、その番号のマーク欄をぬりつぶしなさい。",
    "questions": [
        {
            "number": 1,
            "text": "A: This baseball game is great.\nB: I (　) so, too.",
            "choices": ["speak", "think", "live", "sing"],
            "answer": 2,
            "grammar": "I think so, too.＝「私もそう思う」。野球の試合がすばらしい、という意見に同意する表現。",
            "grammarSimple": "I think so, too. は「わたしもそうおもう」。すばらしいね、に「うん、わたしも！」だよ。",
            "choiceAnalysis": [
                "speak so→「そう話す」では同意の言い方にならない。",
                "○ think＝I think so, too. で「私もそう思う」。",
                "live so→意味が通らない。",
                "sing so→「そう歌う」では文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "speak は「はなす」。そういう言い方しないよ。",
                "○ think がぴったり！「わたしもそうおもう」！",
                "live は「すむ」。合わないよ。",
                "sing は「うたう」。合わないよ。",
            ],
            "questionAudio": "audio/q1.mp3",
            "translation": "A: この野球の試合、すばらしいね。\nB: 私もそう（　）。",
            "choiceTranslations": ["話す", "思う", "住む", "歌う"],
        },
        {
            "number": 2,
            "text": "Dan's mother is a (　). She works at the hospital from Monday to Friday.",
            "choices": ["doctor", "player", "king", "farmer"],
            "answer": 1,
            "grammar": "a doctor＝「医者」。病院で月曜から金曜まで働く＝医者の仕事。",
            "grammarSimple": "doctor は「いしゃ」。びょういんではたらくから、doctor だよ！",
            "choiceAnalysis": [
                "○ doctor＝医者。works at the hospital とつながる。",
                "player＝選手。病院で働く話には合わない。",
                "king＝王。病院の職業として不自然。",
                "farmer＝農夫。病院では働かない。",
            ],
            "choiceAnalysisSimple": [
                "○ doctor がぴったり！「いしゃ」！",
                "player は「せんしゅ」。びょういんじゃないよ。",
                "king は「おうさま」。合わないよ。",
                "farmer は「のうふ」。合わないよ。",
            ],
            "questionAudio": "audio/q2.mp3",
            "translation": "ダンのお母さんは（　）です。月曜から金曜まで病院で働いています。",
            "choiceTranslations": ["医者", "選手", "王", "農夫"],
        },
        {
            "number": 3,
            "text": "I put my books in my (　) before I go to class.",
            "choices": ["locker", "drink", "dictionary", "chopsticks"],
            "answer": 1,
            "grammar": "locker＝「ロッカー」。授業の前に本を入れる場所として自然。",
            "grammarSimple": "locker は「ロッカー」。じゅぎょうのまえにほんをいれるところだよ！",
            "choiceAnalysis": [
                "○ locker＝ロッカー。put books in my locker が自然。",
                "drink＝飲み物。本を入れる場所ではない。",
                "dictionary＝辞書。入れ物の名前ではない。",
                "chopsticks＝箸。本を入れる場所ではない。",
            ],
            "choiceAnalysisSimple": [
                "○ locker がぴったり！「ロッカー」！",
                "drink は「のみもの」。合わないよ。",
                "dictionary は「じしょ」。いれものじゃないよ。",
                "chopsticks は「はし」。合わないよ。",
            ],
            "questionAudio": "audio/q3.mp3",
            "translation": "授業に行く前に、本を自分の（　）に入れます。",
            "choiceTranslations": ["ロッカー", "飲み物", "辞書", "箸"],
        },
        {
            "number": 4,
            "text": "A: Your sister's dress is very (　).\nB: Yes. She likes it very much.",
            "choices": ["rainy", "cute", "tall", "fast"],
            "answer": 2,
            "grammar": "cute＝「かわいい」。ドレスの見た目をほめる言葉として自然。",
            "grammarSimple": "cute は「かわいい」。ドレスがとてもかわいい、だよ！",
            "choiceAnalysis": [
                "rainy＝雨の。服の様子を表す形容詞ではない。",
                "○ cute＝かわいい。very cute dress が自然。",
                "tall＝背が高い。ドレスには当てはまらない。",
                "fast＝速い。ドレスの見た目には合わない。",
            ],
            "choiceAnalysisSimple": [
                "rainy は「あめの」。ドレスには合わないよ。",
                "○ cute がぴったり！「かわいい」！",
                "tall は「せがたかい」。合わないよ。",
                "fast は「はやい」。合わないよ。",
            ],
            "questionAudio": "audio/q4.mp3",
            "translation": "A: お姉さんのドレス、とても（　）ね。\nB: うん。とても気に入ってるよ。",
            "choiceTranslations": ["雨の", "かわいい", "背が高い", "速い"],
        },
        {
            "number": 5,
            "text": "A: When does your summer (　) start?\nB: On July 20.",
            "choices": ["newspaper", "song", "vacation", "candy"],
            "answer": 3,
            "grammar": "summer vacation＝「夏休み」。いつ始まるか？→7月20日、と日付で答える。",
            "grammarSimple": "summer vacation は「なつやすみ」。いつはじまる？→7がつ20にち！",
            "choiceAnalysis": [
                "newspaper＝新聞。夏の新聞が始まる、では不自然。",
                "song＝歌。日付で答える話題に合わない。",
                "○ vacation＝休暇。summer vacation start? が自然。",
                "candy＝キャンディ。文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "newspaper は「しんぶん」。合わないよ。",
                "song は「うた」。合わないよ。",
                "○ vacation がぴったり！「なつやすみ」！",
                "candy は「キャンディ」。合わないよ。",
            ],
            "questionAudio": "audio/q5.mp3",
            "translation": "A: 夏休みはいつ始まるの？\nB: 7月20日だよ。",
            "choiceTranslations": ["新聞", "歌", "休暇", "キャンディ"],
        },
        {
            "number": 6,
            "text": "A: What do you do after school, Cindy?\nB: I play (　).",
            "choices": ["bike", "book", "strawberry", "basketball"],
            "answer": 4,
            "grammar": "play basketball＝「バスケットボールをする」。放課後の活動として自然。",
            "grammarSimple": "play basketball は「バスケをする」。ほうかごになにする？→バスケ！",
            "choiceAnalysis": [
                "play bike→「自転車をする」では不自然。ride a bike が正しい。",
                "play book→「本をする」では意味が通らない。",
                "play strawberry→「いちごをする」では不自然。",
                "○ basketball＝play basketball で「バスケをする」。",
            ],
            "choiceAnalysisSimple": [
                "bike は play しないよ。ride a bike だよ。",
                "book は「ほん」。あそばないよ。",
                "strawberry は「いちご」。合わないよ。",
                "○ basketball がぴったり！「バスケをする」！",
            ],
            "questionAudio": "audio/q6.mp3",
            "translation": "A: シンディー、放課後は何をするの？\nB: （　）をします。",
            "choiceTranslations": ["自転車", "本", "いちご", "バスケットボール"],
        },
        {
            "number": 7,
            "text": "Kengo usually watches the news on TV after dinner, but tonight he is watching a (　) TV show.",
            "choices": ["same", "different", "high", "young"],
            "answer": 2,
            "grammar": "usually ... but tonight a different TV show＝「いつもはニュースだが、今夜は違う番組」。対比の different。",
            "grammarSimple": "different は「ちがう」。いつもはニュースだけど、きょうはちがう番組だよ。",
            "choiceAnalysis": [
                "same＝同じ。but で対比するなら different の方が自然。",
                "○ different＝違う。いつもと違う番組を見ている。",
                "high＝高い。TV show の種類を表さない。",
                "young＝若い。番組の内容を表さない。",
            ],
            "choiceAnalysisSimple": [
                "same は「おなじ」。でも but だからちがうほうがいいよ。",
                "○ different がぴったり！「ちがう番組」！",
                "high は「たかい」。合わないよ。",
                "young は「わかい」。合わないよ。",
            ],
            "questionAudio": "audio/q7.mp3",
            "translation": "ケンゴはたいてい夕食後にテレビでニュースを見ますが、今夜は（　）テレビ番組を見ています。",
            "choiceTranslations": ["同じ", "違う", "高い", "若い"],
        },
        {
            "number": 8,
            "text": "A: Can you come (　) my house at three this afternoon?\nB: Sorry, I can't.",
            "choices": ["of", "for", "to", "out"],
            "answer": 3,
            "grammar": "come to ～＝「〜に来る」。Can you come to my house? で「うちに来られる？」。",
            "grammarSimple": "come to my house は「わたしのいえにくる」。to は「〜へ・〜に」！",
            "choiceAnalysis": [
                "come of→使わない。",
                "come for my house→「家のために来る」では誘いの意味にならない。",
                "○ to＝come to ～ で「〜に来る」。",
                "come out my house→out は「外へ」。誘いの文に合わない。",
            ],
            "choiceAnalysisSimple": [
                "of は come と合わないよ。",
                "for は「〜のために」。きょうの意味じゃないよ。",
                "○ to がぴったり！「いえにくる」！",
                "out は「そとへ」。合わないよ。",
            ],
            "questionAudio": "audio/q8.mp3",
            "translation": "A: 今日の午後3時に、うちに来られる？\nB: ごめん、行けないんだ。",
            "choiceTranslations": ["〜の", "〜のために", "〜に（方向）", "〜の外へ"],
        },
        {
            "number": 9,
            "text": "A: Do you wash the dishes every (　), Tim?\nB: No, only on weekends.",
            "choices": ["night", "cup", "hand", "coin"],
            "answer": 1,
            "grammar": "every night＝「毎晩」。only on weekends（週末だけ）と対比する時間の言い方。",
            "grammarSimple": "every night は「まいばん」。しゅうまつだけ？→まいばんじゃないよ、だね。",
            "choiceAnalysis": [
                "○ night＝every night で「毎晩」。週末だけ、と対比できる。",
                "cup＝カップ。every cup では意味が通らない。",
                "hand＝手。every hand では不自然。",
                "coin＝硬貨。文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "○ night がぴったり！「まいばん」！",
                "cup は「カップ」。合わないよ。",
                "hand は「て」。合わないよ。",
                "coin は「こうか」。合わないよ。",
            ],
            "questionAudio": "audio/q9.mp3",
            "translation": "A: ティム、お皿を毎（　）洗うの？\nB: ううん、週末だけだよ。",
            "choiceTranslations": ["夜", "カップ", "手", "硬貨"],
        },
        {
            "number": 10,
            "text": "A: Can I have a (　) of apple juice, Mom?\nB: Yes. Here you are.",
            "choices": ["glass", "plate", "knife", "fork"],
            "answer": 1,
            "grammar": "a glass of ～＝「〜を1杯」。a glass of apple juice＝リンゴジュースを1杯。",
            "grammarSimple": "a glass of は「〜を1ぱい」。りんごジュースを1ぱいちょうだい！",
            "choiceAnalysis": [
                "○ glass＝a glass of apple juice で「リンゴジュース1杯」。",
                "plate＝皿。a plate of juice では言わない。",
                "knife＝ナイフ。飲み物には合わない。",
                "fork＝フォーク。飲み物には合わない。",
            ],
            "choiceAnalysisSimple": [
                "○ glass がぴったり！「1ぱい」！",
                "plate は「さら」。のむものには合わないよ。",
                "knife は「ナイフ」。合わないよ。",
                "fork は「フォーク」。合わないよ。",
            ],
            "questionAudio": "audio/q10.mp3",
            "translation": "A: ママ、リンゴジュースを1（　）もらえる？\nB: うん。はい、どうぞ。",
            "choiceTranslations": ["コップ（1杯）", "皿", "ナイフ", "フォーク"],
        },
        {
            "number": 11,
            "text": "A: That doll is very nice. How (　) is it?\nB: It's only $5.",
            "choices": ["short", "young", "much", "sad"],
            "answer": 3,
            "grammar": "How much is it?＝「いくらですか」。$5 と答えているので much が正解。",
            "grammarSimple": "How much is it? は「いくら？」。5ドルだよ、とこたえてるね！",
            "choiceAnalysis": [
                "How short→「どれくらい背が低い？」では値段の質問にならない。",
                "How young→「どれくらい若い？」では合わない。",
                "○ much＝How much is it? で「いくら？」。",
                "How sad→「どれくらい悲しい？」では合わない。",
            ],
            "choiceAnalysisSimple": [
                "short は「みじかい・せがひくい」。いくらじゃないよ。",
                "young は「わかい」。いくらじゃないよ。",
                "○ much がぴったり！How much で「いくら」！",
                "sad は「かなしい」。合わないよ。",
            ],
            "questionAudio": "audio/q11.mp3",
            "translation": "A: あの人形、とてもきれいね。いくら（　）？\nB: たった5ドルだよ。",
            "choiceTranslations": ["短い；背が低い", "若い", "いくら（How much）", "悲しい"],
        },
        {
            "number": 12,
            "text": "A: Jenny is a new student. She is (　) France.\nB: That's great. I love France.",
            "choices": ["from", "in", "of", "at"],
            "answer": 1,
            "grammar": "be from ～＝「〜出身である」。She is from France.＝フランス出身です。",
            "grammarSimple": "is from France は「フランスしゅっしん」。from は「〜から・〜出身」！",
            "choiceAnalysis": [
                "○ from＝be from France で「フランス出身」。",
                "in France＝「フランスにいる」。出身の言い方ではない。",
                "of France＝「フランスの」では出身を表さない。",
                "at France→フランス出身には at を使わない。",
            ],
            "choiceAnalysisSimple": [
                "○ from がぴったり！「〜しゅっしん」！",
                "in は「〜のなかにいる」。しゅっしんじゃないよ。",
                "of は「〜の」。しゅっしんには使わないよ。",
                "at は「〜で」。フランスしゅっしんには使わないよ。",
            ],
            "questionAudio": "audio/q12.mp3",
            "translation": "A: ジェニーは新しい生徒です。フランス（　）です。\nB: すごいね。フランスが大好きなんだ。",
            "choiceTranslations": ["〜出身", "〜の中に", "〜の", "〜で（場所）"],
        },
        {
            "number": 13,
            "text": "A: I like this movie.\nB: (　), too.",
            "choices": ["He", "Them", "Me", "We"],
            "answer": 3,
            "grammar": "Me, too.＝「私も（そうです）」。好き、という意見に同意する口語表現。",
            "grammarSimple": "Me, too. は「わたしも！」。えいががすき、に「わたしも！」だよ。",
            "choiceAnalysis": [
                "He, too.→「彼も」になり、自分の意見にならない。",
                "Them, too.→「彼らも」では文脈に合わない。",
                "○ Me, too.＝私も（そう思う・好き）。",
                "We, too.→「私たちも」では会話の流れに合わない。",
            ],
            "choiceAnalysisSimple": [
                "He は「かれ」。わたしじゃないよ。",
                "Them は「かれら」。合わないよ。",
                "○ Me がぴったり！「わたしも」！",
                "We は「わたしたち」。ここでは Me だよ。",
            ],
            "questionAudio": "audio/q13.mp3",
            "translation": "A: この映画、好きだな。\nB: 私（　）。",
            "choiceTranslations": ["彼", "彼ら", "私（Me, too.）", "私たち"],
        },
        {
            "number": 14,
            "text": "A: Alice, (　) quiet!\nB: Sorry, Dad.",
            "choices": ["am", "are", "be", "is"],
            "answer": 3,
            "grammar": "Be quiet!＝「静かにしなさい」。命令文は be 動詞の原形 be で始まる。",
            "grammarSimple": "Be quiet! は「しずかにしなさい」。命令文は be からはじまるよ！",
            "choiceAnalysis": [
                "am quiet→命令文では使わない。",
                "are quiet→二人称の命令には be を使う。",
                "○ be＝Be quiet! で「静かにしなさい」。",
                "is quiet→三人称の形。命令文ではない。",
            ],
            "choiceAnalysisSimple": [
                "am は命令文じゃないよ。",
                "are は「〜しなさい」の形じゃないよ。",
                "○ be がぴったり！Be quiet! で「しずかに」！",
                "is は命令文じゃないよ。",
            ],
            "questionAudio": "audio/q14.mp3",
            "translation": "A: アリス、静かに（　）！\nB: ごめんね、お父さん。",
            "choiceTranslations": ["〜である（am）", "〜である（are）", "〜でありなさい（be）", "〜である（is）"],
        },
        {
            "number": 15,
            "text": "A: (　) phone is this?\nB: It's Bill's.",
            "choices": ["When", "Where", "Whose", "How"],
            "answer": 3,
            "grammar": "Whose phone is this?＝「これは誰の電話？」。It's Bill's.＝ビルのもの、と所有で答える。",
            "grammarSimple": "Whose は「だれの」。だれのでんわ？→ビルのだよ！",
            "choiceAnalysis": [
                "When→「いつ？」では合わない。",
                "Where→「どこ？」では合わない。",
                "○ Whose＝誰の。Whose phone is this? が自然。",
                "How→「どう・どのように？」では合わない。",
            ],
            "choiceAnalysisSimple": [
                "When は「いつ」。だれのじゃないよ。",
                "Where は「どこ」。合わないよ。",
                "○ Whose がぴったり！「だれの」！",
                "How は「どう」。合わないよ。",
            ],
            "questionAudio": "audio/q15.mp3",
            "translation": "A: これは誰の電話（　）？\nB: ビルのだよ。",
            "choiceTranslations": ["いつ", "どこ", "誰の", "どう"],
        },
    ],
}

with open(DATA_PATH, encoding="utf-8") as f:
    data = json.load(f)

others = [s for s in data.get("sections", []) if s.get("name") != "大問1"]
data["sections"] = [section1] + others

with open(DATA_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Wrote section1 ({len(section1['questions'])} questions) to {DATA_PATH}")
