# -*- coding: utf-8 -*-
"""
2026年度 第1回（土曜準会場）英検4級 data.json
大問1（vocabulary型）Q1〜15 — 解説・和訳付き
"""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

DATA_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "data", "grade4", "2026-1-sat", "data.json",
)

section1 = {
    "name": "大問1",
    "nameEn": "Part 1",
    "type": "vocabulary",
    "instruction": "次の(1)から(15)までの( )に入れるのに最も適切なものを1, 2, 3, 4の中から一つ選び、その番号のマーク欄をぬりつぶしなさい。",
    "questions": [
        {
            "number": 1,
            "text": "A: What is that tall (　)?\nB: It's a new school.",
            "choices": ["meter", "building", "coin", "word"],
            "answer": 2,
            "grammar": "tall building＝「高い建物」。答えの It's a new school.（新しい学校だ）から、建物を指している。",
            "grammarSimple": "tall building は「たかいたてもの」。あたらしいがっこうだから、building がぴったり！",
            "choiceAnalysis": [
                "meter＝メートル（長さの単位）。「あの高いメートル」では意味が通らない。",
                "○ building＝建物。tall building が自然。学校も建物の一種。",
                "coin＝硬貨。「高い硬貨」では文脈に合わない。",
                "word＝単語。「高い単語」では意味が通らない。",
            ],
            "choiceAnalysisSimple": [
                "meter は「メートル」。たてものじゃないよ。",
                "○ building がぴったり！「たかいたてもの」！",
                "coin は「こうか」。合わないよ。",
                "word は「ことば」。合わないよ。",
            ],
            "questionAudio": "audio/q1.mp3",
            "translation": "A: あの高い（　）は何？\nB: 新しい学校だよ。",
            "choiceTranslations": ["メートル", "建物", "硬貨", "単語"],
        },
        {
            "number": 2,
            "text": "A: Do you (　) your hands before you eat?\nB: Yes, I do. It's important.",
            "choices": ["read", "drink", "wash", "bring"],
            "answer": 3,
            "grammar": "wash your hands＝「手を洗う」。食べる前の衛生習慣の定番表現。",
            "grammarSimple": "wash your hands は「てをあらう」。たべるまえにてをあらうの、だいじだよ！",
            "choiceAnalysis": [
                "read your hands→「手を読む」では意味が通らない。",
                "drink your hands→「手を飲む」では不自然。",
                "○ wash＝洗う。wash your hands before you eat が自然。",
                "bring your hands→「手を持ってくる」では文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "read は「よむ」。てには合わないよ。",
                "drink は「のむ」。合わないよ。",
                "○ wash がぴったり！「てをあらう」！",
                "bring は「もってくる」。合わないよ。",
            ],
            "questionAudio": "audio/q2.mp3",
            "translation": "A: 食べる前に手を（　）？\nB: うん、するよ。大事だからね。",
            "choiceTranslations": ["読む", "飲む", "洗う", "持ってくる"],
        },
        {
            "number": 3,
            "text": "The pool is fifteen meters (　). It is also very deep.",
            "choices": ["high", "loud", "dry", "long"],
            "answer": 4,
            "grammar": "fifteen meters long＝「15メートルの長さ」。プールの長さを表す。deep（深い）と並ぶ長さの表現。",
            "grammarSimple": "fifteen meters long は「15メートルのながさ」。プールの長さをいうよ。deep（ふかい）とセット！",
            "choiceAnalysis": [
                "high＝高い。長さの単位 meters とは通常 long を使う。",
                "loud＝うるさい。プールの性質として不自然。",
                "dry＝乾いた。水のあるプールには合わない。",
                "○ long＝長い。meters long で長さを表す。",
            ],
            "choiceAnalysisSimple": [
                "high は「たかい」。ながさには long をつかうよ。",
                "loud は「うるさい」。合わないよ。",
                "dry は「かわいた」。プールには合わないよ。",
                "○ long がぴったり！15メートルのながさ！",
            ],
            "questionAudio": "audio/q3.mp3",
            "translation": "そのプールは15メートル（　）だ。とても深い。",
            "choiceTranslations": ["高い", "うるさい", "乾いた", "長い"],
        },
        {
            "number": 4,
            "text": "A: Did you go fishing yesterday, Paul?\nB: Yes. I saw a big fish in the (　).",
            "choices": ["lake", "station", "hat", "sandwich"],
            "answer": 1,
            "grammar": "fish in the lake＝「湖で（湖の中で）魚を見た」。釣り・魚の場所として lake が自然。",
            "grammarSimple": "in the lake は「みずうみのなかで」。おおきなさかなをみたのはみずうみだよ！",
            "choiceAnalysis": [
                "○ lake＝湖。go fishing と fish in the lake がつながる。",
                "station＝駅。魚がいる場所として不自然。",
                "hat＝帽子。in the hat では「帽子の中の魚」になって不自然。",
                "sandwich＝サンドイッチ。文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "○ lake がぴったり！「みずうみ」！",
                "station は「えき」。さかなはいないよ。",
                "hat は「ぼうし」。合わないよ。",
                "sandwich は「サンドイッチ」。合わないよ。",
            ],
            "questionAudio": "audio/q4.mp3",
            "translation": "A: ポール、昨日釣りに行った？\nB: うん。（　）で大きな魚を見たよ。",
            "choiceTranslations": ["湖", "駅", "帽子", "サンドイッチ"],
        },
        {
            "number": 5,
            "text": "Sara's birthday party was on Saturday. She (　) all her friends to her house.",
            "choices": ["looked", "invited", "decided", "hoped"],
            "answer": 2,
            "grammar": "invite ～ to ～＝「〜を〜に招待する」。誕生日パーティーに友達を家に呼ぶ場面。",
            "grammarSimple": "invited は「しょうたいした」。たんじょうびパーティーにともだちをいえによんだよ！",
            "choiceAnalysis": [
                "looked＝見た。looked friends to her house では意味が通らない。",
                "○ invited＝招待した。invite A to B の形。",
                "decided＝決めた。decided friends to では不自然。",
                "hoped＝望んだ。友達を「望む」ではパーティーの文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "looked は「みた」。しょうたいの意味にならないよ。",
                "○ invited がぴったり！「しょうたいした」！",
                "decided は「きめた」。合わないよ。",
                "hoped は「のぞんだ」。合わないよ。",
            ],
            "questionAudio": "audio/q5.mp3",
            "translation": "サラの誕生日パーティーは土曜日だった。彼女は友達全員を家に（　）。",
            "choiceTranslations": ["見た", "招待した", "決めた", "望んだ"],
        },
        {
            "number": 6,
            "text": "Lucas watches the (　) on TV every morning at seven o'clock.",
            "choices": ["night", "news", "wall", "name"],
            "answer": 2,
            "grammar": "watch the news on TV＝「テレビでニュースを見る」。毎朝7時の習慣として自然。",
            "grammarSimple": "watch the news は「ニュースをみる」。まいあさ7じにテレビでニュースだよ！",
            "choiceAnalysis": [
                "night＝夜。watch the night on TV では意味が通らない。",
                "○ news＝ニュース。watch the news on TV が定番。",
                "wall＝壁。テレビで壁を「見る」では不自然。",
                "name＝名前。文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "night は「よる」。ニュースじゃないよ。",
                "○ news がぴったり！「ニュース」！",
                "wall は「かべ」。合わないよ。",
                "name は「なまえ」。合わないよ。",
            ],
            "questionAudio": "audio/q6.mp3",
            "translation": "ルーカスは毎朝7時にテレビで（　）を見る。",
            "choiceTranslations": ["夜", "ニュース", "壁", "名前"],
        },
        {
            "number": 7,
            "text": "A: How many (　) do you have, Kim?\nB: I have six. We're all going to go to the beach this weekend.",
            "choices": ["teeth", "shirts", "cousins", "leaves"],
            "answer": 3,
            "grammar": "cousins＝「いとこ（たち）」。6人いて、みんなで海に行く＝親戚のいとこが6人。",
            "grammarSimple": "cousins は「いとこ」。6人いて、みんなでうみに行くよ！",
            "choiceAnalysis": [
                "teeth＝歯。6本の歯で海に行く話にはならない。",
                "shirts＝シャツ。人数の話として cousins の方が自然。",
                "○ cousins＝いとこ。How many cousins? に答えて I have six. がつながる。",
                "leaves＝葉。6枚の葉では文脈に合わない。",
            ],
            "choiceAnalysisSimple": [
                "teeth は「は」。いとこじゃないよ。",
                "shirts は「シャツ」。ひとりかぞうには合わないよ。",
                "○ cousins がぴったり！「いとこ」6人！",
                "leaves は「はっぱ」。合わないよ。",
            ],
            "questionAudio": "audio/q7.mp3",
            "translation": "A: キム、（　）は何人いるの？\nB: 6人いるよ。今週末みんなで海に行くんだ。",
            "choiceTranslations": ["歯", "シャツ", "いとこ", "葉"],
        },
        {
            "number": 8,
            "text": "A: Will you be in Vancouver for the weekend?\nB: Yes, we'll stay (　) my friend's place.",
            "choices": ["as", "to", "on", "at"],
            "answer": 4,
            "grammar": "stay at ～'s place＝「〜の家に泊まる」。場所を表す前置詞 at。",
            "grammarSimple": "stay at my friend's place は「ともだちのいえにとまる」。at は「〜で・〜に」！",
            "choiceAnalysis": [
                "as＝〜として。stay as my friend's place では不自然。",
                "to＝〜へ。stay to では「泊まる」の意味にならない。",
                "on＝〜の上に。stay on my friend's place は不自然。",
                "○ at＝stay at ～'s place で「〜の家に泊まる」。",
            ],
            "choiceAnalysisSimple": [
                "as は「〜として」。合わないよ。",
                "to は「〜へ」。とまる意味にならないよ。",
                "on は「〜のうえ」。合わないよ。",
                "○ at がぴったり！ともだちのいえにとまる！",
            ],
            "questionAudio": "audio/q8.mp3",
            "translation": "A: 週末はバンクーバーにいるの？\nB: うん、友達の家に泊まるよ。",
            "choiceTranslations": ["〜として", "〜へ", "〜の上に", "〜に（場所）"],
        },
        {
            "number": 9,
            "text": "Kyoko always (　) up early in the morning. She makes her lunch before she goes to work.",
            "choices": ["catches", "forgets", "wakes", "keeps"],
            "answer": 3,
            "grammar": "wake up early＝「早く起きる」。朝の習慣として、出勤前にお弁当を作る流れ。",
            "grammarSimple": "wakes up early は「はやくおきる」。しごまえにおべんとうをつくるんだよ！",
            "choiceAnalysis": [
                "catches up→catch up は「追いつく」。early と結びつかない。",
                "forgets up→forget up は使わない。",
                "○ wakes＝wake up の三単現。always wakes up early が自然。",
                "keeps up→keep up は「続ける・追いつく」。起床の意味にならない。",
            ],
            "choiceAnalysisSimple": [
                "catches は「つかむ・おいつく」。おきる意味じゃないよ。",
                "forgets は「わすれる」。合わないよ。",
                "○ wakes がぴったり！「おきる」！",
                "keeps は「たもつ」。おきる意味じゃないよ。",
            ],
            "questionAudio": "audio/q9.mp3",
            "translation": "キョーコはいつも朝早く（　）。仕事に行く前にお弁当を作る。",
            "choiceTranslations": ["捕まえる；追いつく", "忘れる", "起きる", "保つ；続ける"],
        },
        {
            "number": 10,
            "text": "A: Do we have everything for the picnic on the beach?\nB: Wait a (　). I forgot our baseball caps.",
            "choices": ["number", "reason", "minute", "person"],
            "answer": 3,
            "grammar": "Wait a minute.＝「ちょっと待って」。物を思い出したときの決まり文句。",
            "grammarSimple": "Wait a minute. は「ちょっとまって」。ぼうしをわすれたのをおもいだしたよ！",
            "choiceAnalysis": [
                "Wait a number.→言い回しとして使わない。",
                "Wait a reason.→使わない。",
                "○ minute＝Wait a minute. で「ちょっと待って」。",
                "Wait a person.→使わない。",
            ],
            "choiceAnalysisSimple": [
                "number は「すうじ」。合わないよ。",
                "reason は「りゆう」。合わないよ。",
                "○ minute がぴったり！「ちょっとまって」！",
                "person は「ひと」。合わないよ。",
            ],
            "questionAudio": "audio/q10.mp3",
            "translation": "A: 海辺のピクニックの準備、全部そろってる？\nB: ちょっと（　）。野球帽を忘れた。",
            "choiceTranslations": ["数字", "理由", "分（ちょっと待って）", "人"],
        },
        {
            "number": 11,
            "text": "A: How's Ellen, Ms. Simpson?\nB: She's still sick (　) bed, but she's better.",
            "choices": ["at", "under", "in", "with"],
            "answer": 3,
            "grammar": "sick in bed＝「寝込んでいる・床に就いて具合が悪い」。病気の状態の定番表現。",
            "grammarSimple": "sick in bed は「ねこんでびょうき」。まだねているけど、よくなってきたよ。",
            "choiceAnalysis": [
                "sick at bed→at bed は通常使わない。in bed が正しい。",
                "sick under bed→「ベッドの下で病気」では意味が通らない。",
                "○ in＝sick in bed で「寝込んでいる」。",
                "sick with bed→with bed では意味が通らない。",
            ],
            "choiceAnalysisSimple": [
                "at は sick in bed じゃないよ。",
                "under は「した」。合わないよ。",
                "○ in がぴったり！sick in bed で「ねこんでびょうき」！",
                "with は「〜と」。合わないよ。",
            ],
            "questionAudio": "audio/q11.mp3",
            "translation": "A: エレンはどうですか、シンプソン先生。\nB: まだ（　）で具合が悪いですが、よくなってきました。",
            "choiceTranslations": ["〜で（at）", "〜の下で", "〜で（寝ている）", "〜と一緒に"],
        },
        {
            "number": 12,
            "text": "A: Be kind (　) your brother.\nB: Yes, Mom.",
            "choices": ["to", "on", "at", "in"],
            "answer": 1,
            "grammar": "be kind to ～＝「〜に親切にする」。人に対する態度を表す to。",
            "grammarSimple": "be kind to は「〜にやさしくする」。おとうとにやさしくしなさい、だよ！",
            "choiceAnalysis": [
                "○ to＝be kind to ～ が正しい形。",
                "be kind on→通常使わない。",
                "be kind at→使わない。",
                "be kind in→使わない。",
            ],
            "choiceAnalysisSimple": [
                "○ to がぴったり！be kind to で「やさしく」！",
                "on は合わないよ。",
                "at は合わないよ。",
                "in は合わないよ。",
            ],
            "questionAudio": "audio/q12.mp3",
            "translation": "A: お兄ちゃんに親切にしなさい。\nB: はい、ママ。",
            "choiceTranslations": ["〜に（to）", "〜の上に", "〜で（時・場所）", "〜の中に"],
        },
        {
            "number": 13,
            "text": "I went to the park with my grandmother yesterday. She (　) the names of many trees and flowers there.",
            "choices": ["know", "knew", "knowing", "to know"],
            "answer": 2,
            "grammar": "yesterday があるので過去形 knew。「木や花の名前を知っていた」。",
            "grammarSimple": "knew は know の過去形。きのう、おばあちゃんはきやはなのなまえをしっていたよ。",
            "choiceAnalysis": [
                "know＝現在形。yesterday とは時制が合わない。",
                "○ knew＝過去形。昨日の出来事なので knew。",
                "knowing＝進行形・動名詞。述語として主に使えない。",
                "to know＝不定詞。文の述語として不自然。",
            ],
            "choiceAnalysisSimple": [
                "know は「いま」。きのうには合わないよ。",
                "○ knew がぴったり！「しっていた」！",
                "knowing は文の動詞にならないよ。",
                "to know はそのままでは合わないよ。",
            ],
            "questionAudio": "audio/q13.mp3",
            "translation": "昨日、祖母と公園に行った。彼女はそこでたくさんの木や花の名前を（　）。",
            "choiceTranslations": ["知る（現在）", "知っていた（過去）", "知っている（分詞）", "知るために（不定詞）"],
        },
        {
            "number": 14,
            "text": "Steve, it's already eleven o'clock. Stop (　) the video game and go to bed.",
            "choices": ["play", "plays", "played", "playing"],
            "answer": 4,
            "grammar": "stop ～ing＝「〜するのをやめる」。Stop playing the video game.＝ゲームをやめて寝なさい。",
            "grammarSimple": "stop playing は「〜するのをやめる」。もう11じだから、ゲームをやめてねて！",
            "choiceAnalysis": [
                "stop play→stop の後は動名詞（～ing）が必要。",
                "stop plays→文法的に誤り。",
                "stop played→文法的に誤り。",
                "○ playing＝stop playing で「〜するのをやめる」。",
            ],
            "choiceAnalysisSimple": [
                "play は stop のあとにそのままは使えないよ。",
                "plays は文法がちがうよ。",
                "played は文法がちがうよ。",
                "○ playing がぴったり！stop playing で「やめる」！",
            ],
            "questionAudio": "audio/q14.mp3",
            "translation": "スティーブ、もう11時だよ。ビデオゲームを（　）のをやめて、寝なさい。",
            "choiceTranslations": ["遊ぶ（原形）", "遊ぶ（三単現）", "遊んだ（過去）", "遊ぶのを（動名詞）"],
        },
        {
            "number": 15,
            "text": "A: Can I play video games today, Dad?\nB: Yes, but you must (　) your bedroom first.",
            "choices": ["clean", "cleans", "is cleaning", "cleaned"],
            "answer": 1,
            "grammar": "must + 動詞の原形＝「〜しなければならない」。must clean your bedroom。",
            "grammarSimple": "must clean は「そうじしなきゃ」。ゲームのまえにへやをそうじしてね！",
            "choiceAnalysis": [
                "○ clean＝原形。must の後は必ず原形。",
                "cleans＝三単現。must の後には使えない。",
                "is cleaning＝進行形。must is cleaning は文法的に誤り。",
                "cleaned＝過去形。must cleaned は文法的に誤り。",
            ],
            "choiceAnalysisSimple": [
                "○ clean がぴったり！must のあとはげんけい！",
                "cleans は must のあとに使えないよ。",
                "is cleaning は文法がちがうよ。",
                "cleaned は文法がちがうよ。",
            ],
            "questionAudio": "audio/q15.mp3",
            "translation": "A: 今日、ビデオゲームしていい、お父さん？\nB: うん。でも、先に自分の部屋を（　）しなさい。",
            "choiceTranslations": ["掃除する（原形）", "掃除する（三単現）", "掃除している", "掃除した"],
        },
    ],
}

with open(DATA_PATH, encoding="utf-8") as f:
    data = json.load(f)

others = [s for s in data.get("sections", []) if s.get("name") != "大問1"]
data["sections"] = [section1] + others

with open(DATA_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Wrote section1 ({len(section1['questions'])} questions) to {DATA_PATH}")
