# -*- coding: utf-8 -*-
"""2026年度 第1回（本会場）英検5級 data.json 大問1 Q1〜15"""
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

DATA_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "data", "grade5", "2026-1", "data.json",
)


def mark_ca(items, answer):
    out = []
    for i, text in enumerate(items):
        cleaned = re.sub(r"^[○✅❌]\s*", "", text)
        prefix = "✅" if i + 1 == answer else "❌"
        out.append(f"{prefix} {cleaned}")
    return out


def q(n, text, choices, answer, grammar, grammar_simple, ca, ca_simple, trans, choice_trans):
    return {
        "number": n,
        "text": text,
        "choices": choices,
        "answer": answer,
        "grammar": grammar,
        "grammarSimple": grammar_simple,
        "choiceAnalysis": ca,
        "choiceAnalysisSimple": ca_simple,
        "questionAudio": f"audio/q{n}.mp3",
        "translation": trans,
        "choiceTranslations": choice_trans,
    }


section1 = {
    "name": "大問1",
    "nameEn": "Part 1",
    "type": "vocabulary",
    "instruction": "次の(1)から(15)までの( )に入れるのに最も適切なものを1, 2, 3, 4の中から一つ選び、その番号のマーク欄をぬりつぶしなさい。",
    "questions": [
        q(1,
           "A: What do you do in your free time, John?\nB: I read a (　) every day.",
           ["music", "paint", "newspaper", "lunch"],
           3,
           "read a newspaper＝「新聞を読む」。free time の過ごし方として自然。",
           "newspaper は「しんぶん」。ひまなときにしんぶんをよむんだよ！",
           ["music＝音楽。read a music では意味が通らない。",
            "paint＝ペンキ・絵の具。read a paint では不自然。",
            "newspaper＝新聞。read a newspaper every day が自然。",
            "lunch＝昼食。read a lunch では意味が通らない。"],
           ["music は「おんがく」。read a music じゃないよ。",
            "paint は「えのぐ」。合わないよ。",
            "○ newspaper がぴったり！「しんぶん」！",
            "lunch は「ちゅうしょく」。合わないよ。"],
           "A: ジョン、暇なときは何をするの？\nB: 毎日（　）を読むんだ。",
           ["音楽", "絵の具", "新聞", "昼食"]),
        q(2,
           "Many (　) are waiting for the new pink train. It's very popular.",
           ["books", "teeth", "fruits", "people"],
           4,
           "Many people are waiting＝「多くの人が待っている」。電車を待つ主語として people が自然。",
           "people は「ひとびと」。ピンクの電車をまっているひとがおおいんだよ！",
           ["books＝本。本が待つでは意味が通らない。",
            "teeth＝歯。人が待つ文脈に合わない。",
            "fruits＝果物。are waiting の主語として不自然。",
            "people＝人々。Many people are waiting が自然。"],
           ["books は「ほん」。まてないよ。",
            "teeth は「は」。合わないよ。",
            "fruits は「くだもの」。合わないよ。",
            "○ people がぴったり！「ひとびと」！"],
           "多くの（　）が新しいピンクの電車を待っている。とても人気だ。",
           ["本", "歯", "果物", "人々"]),
        q(3,
           "A: Where is your tennis (　), Hiroki?\nB: It's in my bag, Mom.",
           ["fork", "dictionary", "kite", "racket"],
           4,
           "tennis racket＝「テニスラケット」。かばんの中にあるスポーツ用具。",
           "racket は「ラケット」。テニスのラケットがかばんのなかにあるよ！",
           ["fork＝フォーク。テニス用具ではない。",
            "dictionary＝辞書。スポーツの道具として不自然。",
            "kite＝たこ。テニスとは関係ない。",
            "racket＝ラケット。tennis racket in my bag が自然。"],
           ["fork は「フォーク」。合わないよ。",
            "dictionary は「じしょ」。合わないよ。",
            "kite は「たこ」。合わないよ。",
            "○ racket がぴったり！「ラケット」！"],
           "A: ヒロキ、テニスの（　）はどこ？\nB: かばんの中にあるよ、ママ。",
           ["フォーク", "辞書", "たこ", "ラケット"]),
        q(4,
           "A: Mike, please (　) your coffee before you go to school.\nB: OK, Mom.",
           ["sleep", "drink", "arrive", "talk"],
           2,
           "drink your coffee＝「コーヒーを飲む」。学校に行く前の指示。",
           "drink は「のむ」。がっこうに行くまえにコーヒーをのんでね！",
           ["sleep your coffee→「コーヒーを眠る」では意味が通らない。",
            "drink＝飲む。drink your coffee before school が自然。",
            "arrive your coffee→使わない。",
            "talk your coffee→使わない。"],
           ["sleep は「ねむる」。合わないよ。",
            "○ drink がぴったり！「のむ」！",
            "arrive は「つく」。合わないよ。",
            "talk は「はなす」。合わないよ。"],
           "A: マイク、学校に行く前にコーヒーを（　）てね。\nB: わかった、ママ。",
           ["眠る", "飲む", "着く", "話す"]),
        q(5,
           "Taro likes skiing. He goes to the (　) near his house every winter.",
           ["pool", "station", "library", "mountain"],
           4,
           "goes to the mountain＝「山に行く」。スキーと winter がつながる。",
           "mountain は「やま」。ふゆはやまにスキーに行くんだよ！",
           ["pool＝プール。スキーには合わない。",
            "station＝駅。スキーに行く場所として不自然。",
            "library＝図書館。冬のスキーとは無関係。",
            "mountain＝山。skiing と goes to the mountain が自然。"],
           ["pool は「プール」。スキーじゃないよ。",
            "station は「えき」。合わないよ。",
            "library は「としょかん」。合わないよ。",
            "○ mountain がぴったり！「やま」！"],
           "タロウはスキーが好きだ。毎年冬、家の近くの（　）に行く。",
           ["プール", "駅", "図書館", "山"]),
        q(6,
           "A: Mike, how (　) is that building?\nB: It's 200 meters.",
           ["fast", "cold", "young", "tall"],
           4,
           "how tall is ～?＝「〜はどれくらい高い？」。200 meters が高さの答え。",
           "tall は「たかい」。たてもののたかさをきいてるよ！",
           ["fast＝速い。建物の高さを聞く質問ではない。",
            "cold＝寒い。200 meters という答えと合わない。",
            "young＝若い。建物には使わない。",
            "tall＝高い。how tall ... 200 meters と呼応。"],
           ["fast は「はやい」。たかさじゃないよ。",
            "cold は「さむい」。合わないよ。",
            "young は「わかい」。たてものには使わないよ。",
            "○ tall がぴったり！「たかい」！"],
           "A: マイク、その建物はどれくらい（　）？\nB: 200メートルだよ。",
           ["速い", "寒い", "若い", "高い"]),
        q(7,
           "A: Excuse me, Ms. Brown. Can I go home now?\nB: Yes, John. You can (　) now.",
           ["know", "leave", "take", "eat"],
           2,
           "You can leave now.＝「もう帰っていいよ」。go home への許可。",
           "leave は「かえる」。いまかえっていいよ、って言ってる！",
           ["know now→「今知る」では帰宅の許可にならない。",
            "leave＝去る・帰る。Can I go home? への自然な返答。",
            "take now→文脈に合わない。",
            "eat now→帰る許可の答えにならない。"],
           ["know は「しる」。かえる話じゃないよ。",
            "○ leave がぴったり！「かえる」！",
            "take は「とる」。合わないよ。",
            "eat は「たべる」。合わないよ。"],
           "A: ブラウン先生、もう帰ってもいいですか？\nB: ええ、ジョン。もう（　）っていいわよ。",
           ["知る", "帰る", "取る", "食べる"]),
        q(8,
           "A: Sorry, Mike. I can't go to the movie with you today.\nB: Oh, I (　).",
           ["look", "see", "play", "stand"],
           2,
           "Oh, I see.＝「ああ、わかった」。映画に行けないことを聞いた返事。",
           "I see. は「なるほど」。えいがに行けないってきいたときの返事だよ！",
           ["look＝見る。Oh, I look. では使わない。",
            "see＝I see. で「わかった・なるほど」。",
            "play＝遊ぶ。文脈に合わない。",
            "stand＝立つ。定型の返事にならない。"],
           ["look は「みる」。I see. じゃないよ。",
            "○ see がぴったり！I see. で「なるほど」！",
            "play は「あそぶ」。合わないよ。",
            "stand は「たつ」。合わないよ。"],
           "A: ごめん、マイク。今日は映画に一緒に行けないんだ。\nB: ああ、（　）。",
           ["見る", "わかった（I see）", "遊ぶ", "立つ"]),
        q(9,
           "A: Do you often eat fruit (　) home?\nB: No.",
           ["under", "with", "about", "at"],
           4,
           "at home＝「家で」。eat fruit at home が自然。",
           "at home は「いえで」。くだものをいえでたべる？の at だよ！",
           ["under home→「家の下で」では不自然。",
            "with home→使わない。",
            "about home→「家について」では場所を表さない。",
            "at＝at home で「家で」。"],
           ["under は「〜のした」。合わないよ。",
            "with は「〜といっしょに」。合わないよ。",
            "about は「〜について」。合わないよ。",
            "○ at がぴったり！at home で「いえで」！"],
           "A: 家でよく果物を食べる？\nB: ううん。",
           ["〜の下で", "〜と一緒に", "〜について", "〜で（at home）"]),
        q(10,
           "A: Dad, can we (　) hiking tomorrow?\nB: Sure.",
           ["go", "want", "close", "play"],
           1,
           "go hiking＝「ハイキングに行く」。can we ...? の動詞として go が自然。",
           "go hiking は「ハイキングに行く」。あした行ける？だよ！",
           ["go＝行く。go hiking tomorrow が定番表現。",
            "want hiking→want to go hiking なら可だが、ここでは go が正解。",
            "close hiking→使わない。",
            "play hiking→play はスポーツ名と使うが hiking には通常 go。"],
           ["○ go がぴったり！go hiking！",
            "want だけでは文が成立しないよ。",
            "close は「しめる」。合わないよ。",
            "play hiking はふつう言わないよ。"],
           "A: お父さん、明日ハイキングに（　）？\nB: いいよ。",
           ["行く", "欲しい", "閉める", "遊ぶ"]),
        q(11,
           "Taro goes to the swimming pool (　) school.",
           ["after", "about", "down", "on"],
           1,
           "after school＝「放課後」。プールに行く時間として after が自然。",
           "after school は「ほうかご」。がっこうのあとプールに行くよ！",
           ["after＝〜の後。after school で放課後。",
            "about school→「学校について」では時を表さない。",
            "down school→使わない。",
            "on school→「学校の上に」では不自然。"],
           ["○ after がぴったり！after school！",
            "about は「〜について」。合わないよ。",
            "down は合わないよ。",
            "on は合わないよ。"],
           "タロウは（　）学校、プールに行く。",
           ["〜の後（放課後）", "〜について", "下へ", "〜の上に"]),
        q(12,
           "I (　) up at seven every morning. Then, I have breakfast with my mother.",
           ["sing", "talk", "close", "wake"],
           4,
           "wake up＝「起きる」。at seven every morning とつながる。",
           "wake up は「おきる」。まいあさ7じにおきるんだよ！",
           ["sing up→使わない。",
            "talk up→使わない。",
            "close up→「閉める」では朝の習慣にならない。",
            "wake＝wake up at seven が自然。"],
           ["sing は「うたう」。合わないよ。",
            "talk は「はなす」。合わないよ。",
            "close は「しめる」。合わないよ。",
            "○ wake がぴったり！wake up！"],
           "私は毎朝7時に（　）。それからお母さんと朝食を食べる。",
           ["歌う", "話す", "閉める", "起きる"]),
        q(13,
           "Mr. Ford teaches English. We like (　) class very much.",
           ["his", "he", "him", "us"],
           1,
           "his class＝「彼の授業」。所有格 his が class を修飾。",
           "his は「かれの」。フォード先生のじゅぎょうがすきなんだよ！",
           ["his＝彼の。like his class が正しい。",
            "he class→主格 he は名詞の前に置けない。",
            "him class→目的格 him は名詞の前に置けない。",
            "us class→「私たちの授業」では Ford 先生の授業とずれる。"],
           ["○ his がぴったり！「かれの」！",
            "he は名詞のまえに置けないよ。",
            "him も名詞のまえに置けないよ。",
            "us は「わたしたちの」。先生の授業じゃないよ。"],
           "フォード先生は英語を教える。私たちは（　）の授業がとても好きだ。",
           ["彼の", "彼（主格）", "彼（目的格）", "私たちの"]),
        q(14,
           "A: Nancy, I can't find my eraser. Can I use yours?\nB: Yes. You can use (　).",
           ["I", "my", "me", "mine"],
           4,
           "use mine＝「私の（消しゴム）を使う」。名詞の代わりに所有代名詞 mine。",
           "mine は「わたしのもの」。You can use mine. だよ！",
           ["I＝主格。use I では文法的に誤り。",
            "my＝所有格。use my だけでは名詞が必要。",
            "me＝目的格。use me は「私を使う」となり不自然。",
            "mine＝所有代名詞。You can use mine. が正しい。"],
           ["I は「わたし」主格。合わないよ。",
            "my だけでは名詞がたりないよ。",
            "me は「わたしを」。合わないよ。",
            "○ mine がぴったり！「わたしのもの」！"],
           "A: ナンシー、消しゴムが見つからない。あなたのを使ってもいい？\nB: うん。（　）を使っていいわよ。",
           ["私（主格）", "私の（所有格）", "私を", "私のもの"]),
        q(15,
           "A: Is Kent in the library?\nB: Yes, he (　) there.",
           ["is studying", "are studying", "am studying", "studying"],
           1,
           "he is studying＝「彼は勉強している」。三人称単数＋現在進行形。",
           "is studying は「べんきょうしている」。ケントはとしょかんでべんきょう中だよ！",
           ["is studying＝he と一致する現在進行形。",
            "are studying＝主語 he と一致しない。",
            "am studying＝主語 he と一致しない。",
            "studying＝be動詞がなく文が成立しない。"],
           ["○ is studying がぴったり！「べんきょうしている」！",
            "are は he と合わないよ。",
            "am は he と合わないよ。",
            "studying だけでは文にならないよ。"],
           "A: ケントは図書館にいる？\nB: うん、彼はそこで（　）。",
           ["勉強している（is studying）", "勉強している（are）", "勉強している（am）", "勉強している（be動詞なし）"]),
    ],
}

for qitem in section1["questions"]:
    qitem["choiceAnalysis"] = mark_ca(qitem["choiceAnalysis"], qitem["answer"])

with open(DATA_PATH, encoding="utf-8") as f:
    data = json.load(f)

others = [s for s in data.get("sections", []) if s.get("name") != "大問1"]
data["sections"] = [section1] + others

with open(DATA_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Wrote section1 ({len(section1['questions'])} questions) to {DATA_PATH}")
