# -*- coding: utf-8 -*-
"""Reproduce Grade 5 2026-2 Saturday: booklet pp. 2-5, visually verified."""
import importlib.util
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parent
OUT=ROOT/"data/grade5/2026-2-sat/data.json"

def module(suffix):
    spec=importlib.util.spec_from_file_location(suffix,ROOT/f"gen_g5_2026-2_sat_{suffix}.py")
    result=importlib.util.module_from_spec(spec);spec.loader.exec_module(result)
    return result

# Exact stems/options, bilingual blanks, normal/easy explanations and four
# option-specific reasons. The correct option alone has the existing ○ marker.
ROWS=[
    ("Tom likes (　) very much. He drinks it every morning at breakfast.",
     "トムは (　) が大好きです。毎朝、朝食のときにそれを飲みます。",
     ["bag","dog","school","milk"],["かばん","犬","学校","牛乳"],4,
     "He drinks it（それを飲む）が手がかり。飲めるものは milk（牛乳）。it は前の文の milk を指す。every morning at breakfast は『毎朝、朝食のときに』。2文をつなげて読む。",
     "つぎの文に『それをのむ』とかいてあるよ。のめるのは milk（ぎゅうにゅう）。あさごはんのときに、まいあさのむんだね。",
     ["かばんは飲み物ではない。","犬を飲むとは言わない。","学校は場所で、飲めない。","drinks it とつながる飲み物。"],
     ["かばんはのめないよ。","いぬは、のみものではないね。","がっこうはのむものではないよ。","ぎゅうにゅうなら、のめるね。"]),
    ("I like this park. Many (　) come here.","私はこの公園が好きです。たくさんの (　) がここに来ます。",
     ["people","desks","pencils","trees"],["人々","机","鉛筆","木々"],1,
     "come here は『ここに来る』。公園に来るのは people（人々）。many の後ろは複数を表す名詞を置く。people はそれ自体で複数の人を表し、ここで peoples にはしない。",
     "こうえんに、たくさんのひとがくるよ。people は『ひとびと』。つくえやえんぴつやきが、じぶんであるいてくるのではないね。",
     ["人々が公園に来るという自然な内容。","机が自分で公園へ来る内容ではない。","鉛筆が公園へ来るとは言わない。","公園に木はあっても、木が来るわけではない。"],
     ["こうえんにひとがくるんだね。","つくえは、じぶんでこないよ。","えんぴつがくるおはなしではないよ。","きは、あるいてこないね。"]),
    ("A: Oh no! I can't open this box.\nB: Please (　) again, Anna.",
     "A：困った。この箱を開けられません。\nB：アンナ、もう一度 (　) してください。",
     ["wash","meet","dance","try"],["洗う","会う","踊る","試す・やってみる"],4,
     "箱を開けられない人に、もう一度やってみるよう勧めている。try again は『もう一度試す』。Please＋動詞の原形で丁寧な依頼を表す。again は『再び』で、前の失敗を受ける。",
     "はこがあかないから『もういちどやってみて』といっているよ。try again をセットでおぼえよう。Please がつくと、ていねいにおねがいできるね。",
     ["箱を洗っても、もう一度開けるよう勧める文にはならない。","人に会う話ではない。","踊ることは箱を開ける行動につながらない。","開けることをもう一度試すよう頼んでいる。"],
     ["はこをあらうおはなしではないよ。","だれかにあうことではないよ。","おどることではないよ。","もういちど、やってみるんだね。"]),
    ("A: When does your math (　) start?\nB: It starts at 9:30.",
     "A：あなたの数学の (　) はいつ始まりますか。\nB：9時30分に始まります。",
     ["water","map","desk","class"],["水","地図","机","授業"],4,
     "math class は『数学の授業』。at 9:30 に始まるという返答に合う。When does ... start? は開始時刻を尋ねる。does の後ろの動詞は原形 start、返答では主語 It に合わせて starts。",
     "9じ30ぷんにはじまるのは、さんすう・すうがくのじゅぎょうだね。math class で『すうがくのじゅぎょう』。When は『いつ』だよ。",
     ["数学の水という組合せにはならない。","地図が決まった時刻に始まる話ではない。","机は物で、授業の開始を表せない。","math class が時刻に始まるという内容。"],
     ["おみずのことではないよ。","ちずがはじまるのではないよ。","つくえのことではないよ。","すうがくのじゅぎょうがはじまるんだね。"]),
    ("A: Ted, can you (　) the dog under the tree?\nB: Yes. It's very big.",
     "A：テッド、木の下の犬を (　) か。\nB：はい。とても大きいですね。",
     ["see","open","sing","write"],["見る・見える","開ける","歌う","書く"],1,
     "Can you see ...? は『～が見えますか』。返答の It's very big は犬を見て大きさを伝えている。can の後ろは原形 see。under the tree は犬の場所を表す。",
     "きのしたのいぬが、みえるかきいているよ。see は『みえる』。『とてもおおきいね』といえるのは、いぬがみえているからだね。",
     ["犬が見えるかを聞き、大きさを答えている。","犬を開けるとは言わない。","犬を歌うという使い方ではない。","犬という動物を直接書く話ではない。"],
     ["いぬがみえるか、きいているね。","いぬをあけることはできないよ。","うたをうたうことではないよ。","もじをかくおはなしではないよ。"]),
    ("A: Are you writing a letter?\nB: No. I'm (　) a picture.",
     "A：手紙を書いているのですか。\nB：いいえ。絵を (　)。",
     ["singing","saying","jumping","drawing"],["歌っている","言っている","跳んでいる","描いている"],4,
     "draw a picture は『絵を描く』。今していることなので I'm drawing と、be動詞＋動詞のing形で表す。手紙を書く writing a letter と絵を描く drawing a picture を区別する。",
     "てがみではなく、えをかいているよ。えをかくのは draw。いまかいているので I'm drawing になるね。picture は『え』だよ。",
     ["sing は歌を歌うことで、絵を描く動詞ではない。","say は言葉を言うことで、絵を描く意味はない。","jump は跳ぶことで、picture と結び付かない。","drawing a picture で今、絵を描いている。"],
     ["えをうたうのではないよ。","ことばをいうおはなしではないよ。","とびはねることではないよ。","いま、えをかいているんだね。"]),
    ("A: Cindy, please close the (　).\nB: Sure.","A：シンディ、(　) を閉めてください。\nB：分かりました。",
     ["door","singer","eraser","T-shirt"],["ドア","歌手","消しゴム","Tシャツ"],1,
     "close the door は『ドアを閉める』。close の目的語には、開け閉めできる物が必要。Please＋動詞の原形は丁寧な依頼で、Sure. は『いいですよ』と引き受ける返答。",
     "『しめてください』とおねがいしているよ。しめるものは door（ドア）。Sure. は『いいよ』というこたえだね。",
     ["ドアは開けたり閉めたりする物。","歌手という人を閉めるとは言わない。","消しゴムは開け閉めする物ではない。","Tシャツを close するという表現にはならない。"],
     ["ドアをしめるんだね。","うたうひとを、しめないよ。","けしゴムは、しめるものではないよ。","Tシャツをしめるおはなしではないよ。"]),
    ("A: Can I use your computer, Lisa?\nB: All (　). You can.",
     "A：リサ、あなたのコンピューターを使ってもいいですか。\nB：(　)。いいですよ。",
     ["easy","right","cute","new"],["簡単な","よい・正しい","かわいい","新しい"],2,
     "All right. は『いいですよ』という許可・承諾の表現。Can I ...? は『～してもいいですか』。You can. と使用を認める返答なので、決まり文句 All right が合う。",
     "コンピューターをつかっていいか、きいているよ。All right. は『いいよ』。All と right をセットでおぼえよう。",
     ["All easy は許可を出す決まり文句ではない。","All right と You can がどちらも使用を認める。","かわいさを聞いている会話ではない。","新しいかどうかではなく、使う許可を尋ねている。"],
     ["かんたんかどうかではないよ。","All right. で『いいよ』だね。","かわいいかではないよ。","あたらしいかをきいていないよ。"]),
    ("My sister lives in Osaka. I often go from Tokyo (　) Osaka by train and visit her.",
     "姉（妹）は大阪に住んでいます。私はよく東京から大阪 (　) 電車で行き、彼女を訪ねます。",
     ["to","under","down","up"],["～へ・～まで","～の下に","下へ","上へ"],1,
     "from A to B は『AからBまで』。出発地 Tokyo、行き先 Osaka をつなぐので to。by train は交通手段『電車で』。under は下の場所、down・up は上下の方向で、この組合せにはならない。",
     "とうきょうから、おおさかへいくよ。from Tokyo to Osaka は『とうきょうからおおさかまで』のセット。to は、いくさきをしめすよ。",
     ["from Tokyo to Osaka で出発地と行き先を示す。","大阪の下に行くという内容ではない。","from A down B では二つの場所をつなげられない。","from A up B は行き先を示す形にならない。"],
     ["おおさかへ、だから to だね。","おおさかのした、ではないよ。","したへいくことではないよ。","うえへいくことではないよ。"]),
    ("I (　) up at seven o'clock every morning and go to school.",
     "私は毎朝7時に (　)、学校に行きます。",
     ["get","look","come","make"],["起きる（get up）","見る","来る","作る"],1,
     "get up は『起きる』。毎朝7時に起きて学校に行くという習慣。主語 I なので get を使う。look up は見上げる・調べるなどで、ここで言いたい起床とは違う。up を含むセットで判断する。",
     "まいあさ7じにおきて、がっこうへいくよ。get up は『おきる』。get だけでなく、up といっしょにおぼえよう。",
     ["get up が起床を表し、学校に行く前の行動に合う。","look up は見上げるなどで、起きる意味ではない。","come up は上がる・近づくなどで、起床ではない。","make up は作り上げるなどで、起床を表さない。"],
     ["get up で『おきる』だね。","みあげることではないよ。","くることではないよ。","つくることではないよ。"]),
    ("A: How (　) is your guitar lesson today, Kana?\nB: It is thirty minutes. Let's play in the park after that.",
     "A：カナ、今日のギターのレッスンは (　) ですか。\nB：30分です。その後、公園で遊びましょう。",
     ["old","long","high","sunny"],["年を取った・古い","長い","高い","晴れた"],2,
     "thirty minutes が時間の長さを答えているので How long（どのくらいの長さ）。How old は年齢、How high は高さを尋ねる。after that はレッスンの後のこと。返答の単位 minutes が決め手。",
     "こたえが『30ぷん』だから、じかんのながさをきいているよ。How long は『どのくらいながい？』。ねんれいや、たかさではないね。",
     ["How old は年齢などを尋ね、30分という時間に合わない。","How long でレッスンにかかる時間を尋ねる。","How high は高さを尋ね、minutes では答えない。","sunny は天気で、How sunny はレッスンの長さを尋ねない。"],
     ["なんさい、というしつもんではないよ。","30ぷん、というながさをきいているね。","たかさのことではないよ。","はれかどうかではないよ。"]),
    ("A: I like Japanese music. (　) about you?\nB: I like it, too.",
     "A：私は日本の音楽が好きです。あなたは (　)。\nB：私も好きです。",
     ["Who","What","Where","Which"],["だれ","何","どこ","どちら・どれ"],2,
     "What about you? は『あなたはどうですか』と相手にも同じ話題を尋ねる表現。日本の音楽が好きだと伝えた後、相手の好みを聞いている。返答の too は『～も』。What about を一つの表現として覚える。",
     "じぶんのすきなものをいったあとに『あなたは？』ときいているよ。What about you? をセットでおぼえよう。too は『わたしも』の『も』だね。",
     ["Who about you は相手の好みを尋ねる決まり文句にならない。","What about you で相手にも同じ話題を尋ねる。","Where は場所を尋ねるが、返答は場所ではない。","Which about you はこの場面の尋ね方ではない。"],
     ["だれかをきいていないよ。","『あなたはどう？』ときいているね。","ばしょをきいていないよ。","どれをえらぶか、ではないよ。"]),
    ("A: This video camera is very nice. (　) is it?\nB: It's Ted's.",
     "A：このビデオカメラはとてもいいですね。(　) ですか。\nB：テッドのものです。",
     ["When","Where","How","Whose"],["いつ","どこ","どのように・どう","だれのもの"],4,
     "It's Ted's. は『テッドのものです』。持ち主を尋ねるので Whose is it?（だれのものですか）。Ted's は Ted に所有を表す 's を付けた形。いつ・どこ・方法を尋ねても持ち主の返答にはつながらない。",
     "『テッドのものだよ』とこたえているね。だから『だれのもの？』の Whose。なまえに 's がつくと『そのひとのもの』だよ。",
     ["When は時期を尋ねるが、Ted's は時期ではない。","Where は場所を尋ねるが、Ted's は持ち主。","How は状態・方法などを尋ね、持ち主ではない。","Whose がカメラの持ち主を尋ねる。"],
     ["いつかをきいていないよ。","どこにあるかではないよ。","どうやって、ではないよ。","だれのものかをきいているね。"]),
    ("This notebook isn't yours. It's (　).","このノートはあなたのものではありません。(　) です。",
     ["he","they","I","mine"],["彼は","彼らは・それらは","私は","私のもの"],4,
     "yours（あなたのもの）と対応する所有代名詞 mine（私のもの）を使う。It's mine. は It's my notebook. と同じ意味。he・they・I は主語に使う形で、ここでノートの所有を表せない。",
     "『あなたのものではなく、わたしのもの』といっているよ。mine は『わたしのもの』。my notebook のかわりに、mine だけでいえるね。",
     ["he は人を主語にする形で、彼のものという意味ではない。","they は彼ら・それらを指し、ノートの所有を示さない。","I は私はという主語の形で、私のものにはならない。","mine が my notebook の代わりになる。"],
     ["『かれは』では、もちぬしをいえないよ。","『かれらは』ではないよ。","『わたしは』ではなく『わたしのもの』だよ。","mine で『わたしのもの』だね。"]),
    ("A: Emily, please don't talk in the library. Just (　) quiet.\nB: OK, sorry.",
     "A：エミリー、図書館で話さないでください。ただ静かに (　)。\nB：分かりました。ごめんなさい。",
     ["am","be","is","are"],["be動詞（Iに使う形）","be動詞の原形","be動詞（三人称単数に使う形）","be動詞（you・複数に使う形）"],2,
     "Be quiet. は『静かにしなさい』という命令文。命令文は動詞の原形で始めるため、be動詞も原形 be を使う。主語 you は書かれていないので are ではない。don't talk と同じく図書館での注意。",
     "としょかんだから『しずかにしてね』といっているよ。Be quiet. をセットでおぼえよう。おねがいやちゅういには、もとの形の be をつかうね。",
     ["am は I am の形で、命令文の動詞にはしない。","命令文なので原形 be を使い、Be quiet となる。","is は He is などの形で、命令文に合わない。","相手は you でも、命令文は are ではなく be。"],
     ["I am の am はつかわないよ。","Be quiet. で『しずかにして』だね。","He is の is はつかわないよ。","You are の are ではなく、be だよ。"]),
    ("Sister 1: It's Mom's birthday. (　)\nSister 2: Good idea.",
     "姉妹1：お母さんの誕生日です。(　)\n姉妹2：いい考えですね。",
     ["I can't come.","Let's get some flowers.","That's great.","She's cooking."],
     ["私は来られません。","花を買いましょう。","それはすばらしいですね。","彼女は料理しています。"],2,
     "Good idea. は提案に賛成する返答。母の誕生日なので、Let's get some flowers. と花を買う提案が合う。Let's＋動詞の原形は『～しましょう』。状況の説明だけでは Good idea の受ける提案がない。",
     "おかあさんのたんじょうびに『おはなをかおう』といっているよ。Good idea. は『いいかんがえだね』。Let's は『いっしょに～しよう』だよ。",
     ["来られないことは、誕生日のよい提案にならない。","花を用意する提案に、Good idea と賛成している。","すばらしいと感想を言うだけで、具体的な提案がない。","母が料理中という説明は、賛成する提案ではない。"],
     ["こられない、ではいいかんがえにならないよ。","おはなをかう、というかんがえだね。","かんそうだけで、なにをするかいっていないよ。","りょうりしていることではないよ。"]),
    ("Boy: When do you study English?\nGirl: (　)","男の子：いつ英語を勉強しますか。\n女の子：(　)",
     ["With my friends.","For two hours.","By bus.","Before school."],
     ["友達と一緒に。","2時間。","バスで。","学校が始まる前に。"],4,
     "When は勉強する時期・時刻を尋ねるので Before school（学校が始まる前に）。For two hours は時間の長さで、How long に答える表現。誰と・交通手段では When の答えにならない。",
     "When は『いつ』だよ。『がっこうがはじまるまえ』なら、いつかがわかるね。『2じかん』は、いつではなく、じかんのながさだよ。",
     ["一緒に勉強する相手を答え、時期を答えていない。","勉強する長さであって、いつするかではない。","交通手段で、勉強の時期に合わない。","学校が始まる前という時期を答えている。"],
     ["だれと、というこたえだよ。","どのくらいながく、というこたえだよ。","のりもののことではないよ。","がっこうのまえ、というじかんだね。"]),
    ("Girl: Mom, what are you reading?\nMother: (　)","女の子：お母さん、何を読んでいるのですか。\n母：(　)",
     ["In the living room.","That's OK.","This one, please.","Today's newspaper."],
     ["居間で。","大丈夫ですよ。","これをお願いします。","今日の新聞です。"],4,
     "what are you reading? は今、読んでいる物を尋ねる。Today's newspaper（今日の新聞）なら読んでいる物を具体的に答えられる。場所の説明や注文・許可の表現では質問に答えていない。",
     "おかあさんが『なにをよんでいるか』きいているよ。こたえは『きょうのしんぶん』。へやのばしょをきいているのではないね。",
     ["読む場所で、何を読んでいるかには答えていない。","大丈夫という返答では、読む物が分からない。","物を選んで頼む表現で、読んでいる物の説明ではない。","読んでいる物が今日の新聞だと答えている。"],
     ["どこのへやか、ではないよ。","だいじょうぶ、だけではわからないね。","えらんでおねがいすることではないよ。","きょうのしんぶんをよんでいるんだね。"]),
    ("Teacher: Is this your textbook, Jacob?\nStudent: (　) Thank you, Ms. Williams.",
     "先生：ジェイコブ、これはあなたの教科書ですか。\n生徒：(　) ありがとうございます、ウィリアムズ先生。",
     ["That's good.","I'm not going.","No, he isn't.","Yes, it is."],
     ["それはよいですね。","私は行きません。","いいえ、彼はそうではありません。","はい、そうです。"],4,
     "Is this ...? で教科書について確認しているので、返答は Yes, it is.。物を指す this を返答では it に置き換える。Thank you が、自分の教科書を確認してもらった場面に合う。he は男性を指すので教科書には使わない。",
     "『これはあなたのきょうかしょ？』に『はい、そうです』とこたえるよ。きょうかしょは、ひとではないから it。Yes, it is. のセットだね。",
     ["感想だけでは、自分の教科書かという確認に答えない。","行くかどうかを尋ねているわけではない。","he は男性を指すので、教科書の返答に合わない。","this を it に置き換え、教科書の確認に答える。"],
     ["よいかどうかではなく、じぶんのものかをきいているよ。","いくかどうかではないよ。","きょうかしょは、おとこのひとではないね。","it できょうかしょのことをこたえるね。"]),
    ("Boy: (　) Mrs. Smith. Is John home?\nWoman: Yes, he is. Come in.",
     "男の子：(　)、スミスさん。ジョンは家にいますか。\n女性：はい、います。どうぞ入ってください。",
     ["Good evening,","At ten thirty,","It's good,","In the cafeteria,"],
     ["こんばんは、","10時30分に、","それはよいです、","食堂で、"],1,
     "家を訪ね、Mrs. Smith と名前を呼びかける前にはあいさつ Good evening（こんばんは）が合う。Is John home? でジョンがいるか確認し、Come in. と招かれている。選択肢末尾のコンマも原文どおりにつなぐ。",
     "ジョンのいえにきて、まず『こんばんは、スミスさん』とあいさつしているよ。Good evening は『こんばんは』。Come in. は『はいってね』だよ。",
     ["訪問時のあいさつを名前の前に置く。","時刻だけでは訪問のあいさつにならない。","よいという感想では名前への呼びかけにならない。","食堂という場所は、家を訪ねるあいさつではない。"],
     ["まず、こんばんはとあいさつするね。","じかんをいうのではないよ。","よいというかんそうではないよ。","しょくどうのばしょではないよ。"]),
]

def build():
    o,m=module("order"),module("materials")
    qs=[]
    for n,(text,ja,choices,meanings,answer,grammar,simple,reasons,easy) in enumerate(ROWS,1):
        qs.append(dict(number=n,text=text,translation=ja,choices=choices,choiceTranslations=meanings,
                       answer=answer,grammar=grammar,grammarSimple=simple,
                       choiceAnalysis=[("○ " if i==answer else "")+f"{c}＝{t}。{why}" for i,(c,t,why) in enumerate(zip(choices,meanings,reasons),1)],
                       choiceAnalysisSimple=[("○ " if i==answer else "")+f"{t}。{why}" for i,(t,why) in enumerate(zip(meanings,easy),1)],questionAudio=f"audio/q{n}.mp3"))
    sections=[
        dict(name="大問1",nameEn="Part 1",type="vocabulary",instruction="次の(1)から(15)までの(　)に入れるのに最も適切なものを1，2，3，4の中から一つ選び，その番号のマーク欄をぬりつぶしなさい。",questions=qs[:15]),
        dict(name="大問2",nameEn="Part 2",type="vocabulary",instruction="次の(16)から(20)までの会話について，(　)に入れるのに最も適切なものを1，2，3，4の中から一つ選び，その番号のマーク欄をぬりつぶしなさい。",questions=qs[15:]),
        dict(name="大問3",nameEn="Part 3",type="sentence-order",instruction="次の(21)から(25)までの日本文の意味を表すように①から④までを並べかえて□の中に入れなさい。そして，1番目と3番目にくるものの最も適切な組合せを1，2，3，4の中から一つ選び，その番号のマーク欄をぬりつぶしなさい。※ただし，(　)の中では，文のはじめにくる語も小文字になっています。",questions=o.questions()),
    ]
    listening=[1,1,1,2,1,1,2,2,3,2,4,4,2,4,4,2,1,2,1,2,3,3,1,1,3]
    return dict(grade="grade5",year="2026",session="2026-2-sat",exam="2026-2-sat",
                title="英検5級 2026年度 第2回（土曜準会場）",sections=sections,
                listening={f"part{i}":dict(zip(map(str,range(a+1,b+1)),listening[a:b])) for i,(a,b) in enumerate([(0,10),(10,15),(15,25)],1)},
                vocabulary=m.vocabulary(),lessonPlan=m.lessonplan(sections))

if __name__=="__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(json.dumps(build(),ensure_ascii=False,indent=4)+"\n",encoding="utf-8")
    print(OUT)
